version: 2

updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
      time: "04:00"
    open-pull-requests-limit: 10
    groups:
      backend:
        patterns:
          - "*"
    ignore:
      - dependency-name: "org.jetbrains.kotlin:kotlin-gradle-plugin"
        versions: ["2.0.0"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
      time: "04:00"
