package no.nav.tilleggsstonader.kontrakter.aktivitet

/**
 * Alle aktiviteter fra arena - `select * from ram_aktivitettype`
 *
 * Dette uttrekket kommer fra Dagbjørn, som har tilgang til alle rader.
 * Vi har kun tilgang på de rader som vi har en kobling til fra våre saker
 * Alle er tatt inn for å kunne filtrere vekk de som er i en gitt gruppe då API'et til arena svarer med alle typer
 *
 * Denne mappingen gjør det mulig å hente ut aktiviteter som kun tilhører gruppen TILTAK som er det som de ønsker å vise
 */
enum class TypeAktivitet(val gruppe: GruppeAktivitet, val beskrivelse: String, val rettTilStønad: Boolean) {
    AAPLOK(GruppeAktivitet.VEIL, "informasjonsmøte om arbeidsavklaringspenger", false),
    ABIST(GruppeAktivitet.TLTAK, "Arbeid med Bistand (AB)", true),
    ABOPPF(GruppeAktivitet.TLTAK, "Arbeid med bistand A oppfølging", false),
    ABTBOPPF(GruppeAktivitet.TLTAK, "Arbeid med bistand B", false),
    ABUOPPF(GruppeAktivitet.TLTAK, "Arbeid med bistand A utvidet oppfølging", false),
    AGLOK(GruppeAktivitet.VEIL, "informasjonsmøte om attføring", false),
    AILOK(GruppeAktivitet.VEIL, "Lokal - Informasjon om Attf Individuelt", false),
    AKTPLAN(GruppeAktivitet.SAK, "Aktivitetsplan og oppfølging", false),
    AKTSYK_IA(GruppeAktivitet.SPES, "SF2 - Aktiv sykmelding, IA-avtale", false),
    AKTSYK_SA(GruppeAktivitet.SPES, "SF3 - Aktiv sykmelding, ikke IA-avtale", false),
    AMBF1(GruppeAktivitet.TLTAK, "AMB Avklaring (fase 1)", false),
    AMBF2(GruppeAktivitet.TLTAK, "Kvalifisering i arbeidsmarkedsbedrift", true),
    AMBF3(GruppeAktivitet.TLTAK, "Tilrettelagt arbeid i arbeidsmarkedsbedrift", false),
    AMO(GruppeAktivitet.TLTAK, "Arbeidsmarkedsopplæring (AMO)", true),
    AMOB(GruppeAktivitet.TLTAK, "Arbeidsmarkedsopplæring (AMO) i bedrift", true),
    AMOE(GruppeAktivitet.TLTAK, "Arbeidsmarkedsopplæring (AMO) enkeltplass", true),
    AMOY(GruppeAktivitet.TLTAK, "Arbeidsmarkedskurs (AMO) yrkeshemmede", false),
    ANNET(GruppeAktivitet.EGEN, "Annen aktivitet", false),
    ARBDOGNSM(GruppeAktivitet.TLTAK, "Arbeidsrettet rehabilitering (døgn) - sykmeldt arbeidstaker", true),
    ARBEID(GruppeAktivitet.A14A, "Arbeid og oppfølging", false),
    ARBFORB(GruppeAktivitet.TLTAK, "Arbeidsforberedende trening (AFT)", true),
    ARBPVURD(GruppeAktivitet.TLTAK, "Arbeidsplassvudering", false),
    ARBRDAGSM(GruppeAktivitet.TLTAK, "Arbeidsrettet rehabilitering (dag) - sykmeldt arbeidstaker", true),
    ARBRRDOGN(GruppeAktivitet.TLTAK, "Arbeidsrettet rehabilitering (døgn)", true),
    ARBRRHBAG(GruppeAktivitet.TLTAK, "Arbeidsrettet rehabilitering", false),
    ARBRRHBSM(GruppeAktivitet.TLTAK, "Arbeidsrettet rehabilitering - sykmeldt arbeidstaker", false),
    ARBRRHDAG(GruppeAktivitet.TLTAK, "Arbeidsrettet rehabilitering (dag)", true),
    ARBTILARBT(GruppeAktivitet.TLTAK, "Arbeidsrettede tiltak - Arbeidstrening", false),
    ARBTILFORM(GruppeAktivitet.TLTAK, "Arbeidsrettede tiltak - Lønntilskudd", false),
    ARBTILKVAL(GruppeAktivitet.TLTAK, "Arbeidsrettede tiltak - Kvalifisering", false),
    ARBTILOPPF(GruppeAktivitet.TLTAK, "Arbeidsrettede tiltak - Oppfølgingstiltak", false),
    ARBTILTAV(GruppeAktivitet.TLTAK, "Arbeidsrettede tiltak - Avklaring", false),
    ARBTILTBE(GruppeAktivitet.TLTAK, "Arbeidsrettede tiltak - Behandling/rehabilitering", false),
    ARBTILTILR(GruppeAktivitet.TLTAK, "Arbeidsrettede tiltak - Tilrettelagt arbeid", false),
    ARBTREN(GruppeAktivitet.TLTAK, "Arbeidstrening", true),
    ARBTRENA(GruppeAktivitet.EGEN, "Arbeidstrening hos annen arbeidsgiver", false),
    ARBTRENE(GruppeAktivitet.EGEN, "Arbeidstrening hos egen arbeidsgiver", false),
    ARBUTPRO(GruppeAktivitet.TLTAK, "Arbeidsutprøving", false),
    ARKANNET(GruppeAktivitet.ARK, "ARK Annet", false),
    ARKARBUTRD(GruppeAktivitet.ARK, "ARK Arbeidsrettet utredning", false),
    ARKKARVEIL(GruppeAktivitet.ARK, "ARK Utvidet karriereveiledning", false),
    ARKSNTRJOB(GruppeAktivitet.ARK, "ARK Senter for jobbmestring", false),
    ARKVEILEND(GruppeAktivitet.ARK, "ARK Veiledning og endringsarbeid", false),
    ASV(GruppeAktivitet.TLTAK, "Arbeidssamvirke (ASV)", false),
    ASYKM(GruppeAktivitet.SPES, "Aktiv sykmelding", false),
    ATG(GruppeAktivitet.TLTAK, "Arbeidstreningsgrupper", false),
    AVKLARAG(GruppeAktivitet.TLTAK, "Avklaring", true),
    AVKLARKV(GruppeAktivitet.TLTAK, "Avklaring av kortere varighet", false),
    AVKLARSP(GruppeAktivitet.TLTAK, "Avklaring - sykmeldt arbeidstaker", true),
    AVKLARSV(GruppeAktivitet.TLTAK, "Avklaring i skjermet virksomhet", true),
    AVKLARUS(GruppeAktivitet.TLTAK, "Avklaring", false),
    AVRUSING(GruppeAktivitet.SPES, "Avrusing", false),
    AVTAKT(GruppeAktivitet.EGEN, "Avtale om aktivitet", false),
    GSYKM(GruppeAktivitet.SPES2, "Gradert sykmelding", false),
    GVIK(GruppeAktivitet.SAK, "Godkjenning av vikar", false),
    HENVISARK(GruppeAktivitet.SAK, "Veiledning ved Nav Arbeidsrådgivning", false),
    HJOMARBP(GruppeAktivitet.SPES2, "Hjelpemidler og ombygging på arbeidsplass", false),
    HOYEREUTD(GruppeAktivitet.TLTAK, "Høyere utdanning", true),
    IAPLASS(GruppeAktivitet.TLTAK, "IA-plass", false),
    IA_ANPLAN(GruppeAktivitet.SAK, "IA Analyse og plan", false),
    IA_BIST(GruppeAktivitet.SAK, "IA 02 Målrettet IA-arbeid fra Nav Arbeidslivssenter", false),
    IA_EVAL(GruppeAktivitet.SAK, "IA Evaluering", false),
    IA_FJERN(GruppeAktivitet.SAK, "IA Fjern IA-status for arbeidsgiver", false),
    IA_HANDL(GruppeAktivitet.SAK, "IA Handling", false),
    IA_OPPST(GruppeAktivitet.SAK, "IA Oppstart/restart", false),
    IA_REKR(GruppeAktivitet.SAK, "01 Rekruttering av enkeltvirksomheter", false),
    REGDIAL2(GruppeAktivitet.SAK, "Registrer resultet fra dialogmøte2", false),
    REHAB(GruppeAktivitet.SPES2, "Rehabilitering", false),
    REKAVTL(GruppeAktivitet.ANN, "Rekrutteringsavtale", false),
    REKBISTNOR(GruppeAktivitet.ANN, "Møte rekrutteringsbistand", false),
    REKEØS(GruppeAktivitet.ANN, "Rekrutteringsbistand i EØS-området", false),
    REKRE(GruppeAktivitet.ANN, "Rekrutteringsreise", false),
    REKREA(GruppeAktivitet.EGEN, "Rekreasjon", false),
    RESPROF(GruppeAktivitet.SAK, "Ressursprofil og arbeidsevnevurdering", false),
    RSKJ(GruppeAktivitet.SAK, "Reg. ved skjerma sysselsetting", false),
    RUSBEH(GruppeAktivitet.SPES2, "Rusbehandling", false),
    RVIK(GruppeAktivitet.SAK, "Kompetansekartlegging  vikar", false),
    SAMARBAVT(GruppeAktivitet.ANN, "Samarbeidsavtale", false),
    SAMMO(GruppeAktivitet.ANN, "Samarbeidsmøte", false),
    SAMREKR(GruppeAktivitet.ANN, "Samarbeidsmøte rekrutteringsbistand", false),
    SAMT(GruppeAktivitet.SPES, "Samtale", false),
    SAMTILT(GruppeAktivitet.ANN, "Samarbeidsmøte tiltak", false),
    SBLPERSON(GruppeAktivitet.SAK, "Motta selvregistrert person", false),
    SOKJOBB(GruppeAktivitet.ADMO, "Søke annen jobb", false),
    SOSTREME(GruppeAktivitet.A14A, "Sosial trening og mestring", false),
    SPA(GruppeAktivitet.TLTAK, "Spa prosjekter", false),
    SP_DIALOG1(GruppeAktivitet.SPES, "SF4 - Dialogmøte 1 (i regi av arbeidsgiver)", false),
    SP_DIALOG2(GruppeAktivitet.SPES, "Dialogmøte 2 (i regi av Nav)", false),
    SP_DIALOG3(GruppeAktivitet.SPES, "Dialogmøte 3 (i regi av Nav)", false),
    STATLAERL(GruppeAktivitet.TLTAK, "Lærlinger i statlige etater", false),
    SUPPEMP(GruppeAktivitet.TLTAK, "Supported Employment", true),
    SYSSLANG(GruppeAktivitet.TLTAK, "Sysselsettingstiltak for langtidsledige", false),
    SYSSOFF(GruppeAktivitet.TLTAK, "Sysselsettingstiltak i offentlig sektor for yrkeshemmede", false),
    T01(GruppeAktivitet.IAA, "01 IA Tjeneste: Rekruttering av enkeltvirksomhet", false),
    T02(GruppeAktivitet.IAA, "02 IA Tjeneste: Gjennomføre analyse og planlegging av IA-arbeidet", false),
    T03(GruppeAktivitet.IAA, "03 IA Tjeneste: Bistå i rekruttering/inkludering/oppfølging av person", false),
    T04(
        GruppeAktivitet.IAA,
        "04 IA Tjeneste: Informere og veilede i bruk av virkemidler for et mer inkluderende arbeidsliv",
        false,
    ),
    T05(GruppeAktivitet.IAA, "05 IA Tjeneste: Bistå i systemrettet sykefraværsoppfølging", false),
    T06(GruppeAktivitet.IAA, "06 IA Tjeneste: Veilede i IA-ledelse", false),
    T07(GruppeAktivitet.IAA, "07 IA Tjeneste: Veilede i helsefremmende IA-arbeid", false),
    T08(
        GruppeAktivitet.IAA,
        "08 IA Tjeneste: Bistå i systemrettet arbeid for å inkludere personer som står utenfor arbeidslivet",
        false,
    ),
    T09(GruppeAktivitet.IAA, "09 IA Tjeneste: Bistå i å utforme seniorpolitikk i et livsfaseperspektiv", false),
    T10(GruppeAktivitet.IAA, "10 IA Tjeneste: Måle og evaluere måloppnåelse i IA-arbeidet", false),
    TEKNTILR(GruppeAktivitet.TLTAK, "Teknisk tilrettelegging", false),
    TELKO(GruppeAktivitet.ANN, "Telefonkontakt", false),
    TEST(GruppeAktivitet.SPES, "Testing", false),
    TIA002(GruppeAktivitet.IAA, "02 IA Tjeneste: Forebyggende Arbeidsmiljøarbeid", false),
    TIA005(GruppeAktivitet.IAA, "03 IA Tjeneste: HelseIArbeid    ", false),
    TIA006(GruppeAktivitet.IAA, "01 IA Tjeneste: Redusere sykefravær", false),
    TIA02(GruppeAktivitet.IAA, "02 IA Tjeneste: Mål og handlingsplan", false),
    TIA05(GruppeAktivitet.IAA, "03 IA Tjeneste: Forebygge og redusere sykefravær", false),
    TIA06(GruppeAktivitet.IAA, "01 IA Tjeneste: IA-veiledning", false),
    TIA08(GruppeAktivitet.IAA, "04 IA Tjeneste: Rekruttere nye medarbeidere", false),
    TIA09(GruppeAktivitet.IAA, "05 IA Tjeneste: Senior og livsfasearbeid", false),
    TIA10(GruppeAktivitet.IAA, "06 IA Tjeneste: Måle og evaluere", false),
    BEDRBES(GruppeAktivitet.ANN, "Bedriftsbesøk", false),
    BEDRU(GruppeAktivitet.ANN, "Bedriftsundersøkelsen", false),
    BEDRUNDER(GruppeAktivitet.ANN, "Bedriftsundersøkelse", false),
    BEHUTRPS(GruppeAktivitet.TLTAK, "Behandling for lettere psykiske lidelser", false),
    BIA(GruppeAktivitet.TLTAK, "Bedriftsintern attføring", false),
    BIO(GruppeAktivitet.TLTAK, "Bedriftsintern opplæring (BIO)", false),
    BOTRENING(GruppeAktivitet.EGEN, "Botrening", false),
    BT01(GruppeAktivitet.IAA, "Basistjeneste 01 - Forankring og oppstart av IA-arbeidet", false),
    BT02(GruppeAktivitet.IAA, "Basistjeneste 02 - Ledelse", false),
    BT03(GruppeAktivitet.IAA, "Basistjeneste 03 - Fravær til nærvær", false),
    BT04(GruppeAktivitet.IAA, "Basistjeneste 04 - Sykefraværsoppfølging", false),
    BT05(GruppeAktivitet.IAA, "Basistjeneste 05 - Kommunikasjon og samtaletrening", false),
    BT06(GruppeAktivitet.IAA, "Basistjeneste 06 - En samtale om arbeidsmuligheter - funksjonsvurdering", false),
    BT07(GruppeAktivitet.IAA, "Basistjeneste 07 - Hjelp i vanskelige enkeltsaker", false),
    BT08(GruppeAktivitet.IAA, "Basistjeneste 08 - Livsfasepolitikk", false),
    BT09(GruppeAktivitet.IAA, "Basistjeneste 09 - Arbeidstakere med redusert funksjonsevne", false),
    BT10(GruppeAktivitet.IAA, "Basistjeneste 10 - Økonomiske virkemidler", false),
    BT11(GruppeAktivitet.IAA, "Basistjeneste 11 - Annet", false),
    DGLOK(GruppeAktivitet.VEIL, "informasjonsmøte om dagpenger", false),
    DIGIOPPARB(GruppeAktivitet.TLTAK, "Digitalt jobbsøkerkurs for arbeidsledige (jobbklubb)", true),
    DILOK(GruppeAktivitet.VEIL, "Lokal - Informasjon om DP Individuelt", false),
    DIVTILT(GruppeAktivitet.TLTAK, "Diverse tiltak", false),
    EDEL(GruppeAktivitet.EGEN, "Deltidsjobb", false),
    EDKORT(GruppeAktivitet.EGEN, "Kortvarig deltidsjobb", false),
    EFER(GruppeAktivitet.EGEN, "Ferie", false),
    EFRV(GruppeAktivitet.EGEN, "Fravær", false),
    EFUL(GruppeAktivitet.EGEN, "Fulltidsjobb", false),
    EGENTREN(GruppeAktivitet.EGEN, "Egentrening", false),
    EKORTJ(GruppeAktivitet.EGEN, "Kortvarig fulltidsjobb", false),
    EKSPEBIST(GruppeAktivitet.TLTAK, "Ekspertbistand", false),
    EMED(GruppeAktivitet.EGEN, "Medisinsk behandling / utredning", false),
    EMIL(GruppeAktivitet.EGEN, "Førstegangstjenste", false),
    ENKELAMO(GruppeAktivitet.TLTAK, "Enkeltplass AMO", true),
    ENKFAGYRKE(GruppeAktivitet.TLTAK, "Enkeltplass Fag- og yrkesopplæring VGS og høyere yrkesfaglig utdanning", true),
    EPER(GruppeAktivitet.EGEN, "Permisjon", false),
    EPFI(GruppeAktivitet.EGEN, "Permittert i fiskeindustrien", false),
    EPMT(GruppeAktivitet.EGEN, "Permittert", false),
    EPOST(GruppeAktivitet.ANN, "E-post eller SMS", false),
    ESYK(GruppeAktivitet.EGEN, "Sykdom", false),
    ETAB(GruppeAktivitet.TLTAK, "Egenetablering", true),
    ETTERV(GruppeAktivitet.SPES2, "Ettervern", false),
    EUTD(GruppeAktivitet.EGEN, "Egenfinansiert utdanning", false),
    FDIALOG2(GruppeAktivitet.SAK, "Forbered dialogmøte 2", false),
    FLEKSJOBB(GruppeAktivitet.TLTAK, "Fleksibel jobb - lønnstilskudd av lengre varighet", false),
    FORSAMOENK(GruppeAktivitet.TLTAK, "Forsøk AMO enkeltplass", true),
    FORSAMOGRU(GruppeAktivitet.TLTAK, "Forsøk AMO gruppe", false),
    FORSFAGENK(GruppeAktivitet.TLTAK, "Forsøk fag- og yrkesopplæring enkeltplass", true),
    FORSFAGGRU(GruppeAktivitet.TLTAK, "Forsøk fag- og yrkesopplæring gruppe", true), // overstyrer false fra Arena
    FORSHOYUTD(GruppeAktivitet.TLTAK, "Forsøk høyere utdanning", true),
    FORSOPPLEV(GruppeAktivitet.TLTAK, "Forsøk opplæringstiltak av lengre varighet", true),
    FRIMELD(GruppeAktivitet.ADMO, "Friskmelding", false),
    FRISKMELDT(GruppeAktivitet.SPES, "SF5 - Friskmeldt til arbeidsformidling i sykepengeperioden", false),
    FUNKASS(GruppeAktivitet.SPES2, "Funksjonsassistent", false),
    FUNKSJASS(GruppeAktivitet.TLTAK, "Funksjonsassistanse", false),
    GBDR(GruppeAktivitet.ANN, "Planlegge og gjennomføre bedriftsbesøk", false),
    GRADSYK(GruppeAktivitet.ADMO, "Gradert sykmelding", false),
    GRUFAGYRKE(GruppeAktivitet.TLTAK, "Gruppe Fag- og yrkesopplæring VGS og høyere yrkesfaglig utdanning", true),
    GRUPPEAMO(GruppeAktivitet.TLTAK, "Gruppe AMO", true),
    LESEHLP(GruppeAktivitet.SPES2, "Lese- og sekretærhjelp", false),
    LONNTIL(GruppeAktivitet.TLTAK, "Tidsbegrenset lønnstilskudd", false),
    LONNTILAAP(GruppeAktivitet.TLTAK, "Arbeidsavklaringspenger som lønnstilskudd", false),
    LONNTILL(GruppeAktivitet.TLTAK, "Lønnstilskudd av lengre varighet", false),
    LONNTILS(GruppeAktivitet.TLTAK, "Lønnstilskudd", false),
    MEDBEH(GruppeAktivitet.ADMO, "Fortsatt medisinsk behandling", false),
    MEDBEHI(GruppeAktivitet.SPES2, "Medisinsk behandling - institusjon", false),
    MEDBEHP(GruppeAktivitet.SPES2, "Medisinsk behandling - poliklinisk", false),
    MEDBERE(GruppeAktivitet.A14A, "Medisinsk behandling og rehabilitering", false),
    MENTOR(GruppeAktivitet.TLTAK, "Mentor", false),
    MESSE(GruppeAktivitet.VEIL, "jobbmesse", false),
    MIDLONTIL(GruppeAktivitet.TLTAK, "Midlertidig lønnstilskudd", false),
    M_PERSON(GruppeAktivitet.SAK, "Motta person", false),
    MØTETILT(GruppeAktivitet.ANN, "Møte tiltak", false),
    NETTAMO(GruppeAktivitet.TLTAK, "Nettbasert arbeidsmarkedsopplæring (AMO)", true),
    NOINT(GruppeAktivitet.VEIL, "norsktest ved Nav Intro", false),
    NOROPPL(GruppeAktivitet.SPES2, "Norskopplæring", false),
    OARB(GruppeAktivitet.SAK, "Gjennomfør oppfølgning arbeidssøker", false),
    OHPL(GruppeAktivitet.SAK, "Følg opp handlingsplan", false),
    OPPDITINFO(GruppeAktivitet.SAK, "Innhent/oppdater tilleggsinformasjon", false),
    OPPFARB(GruppeAktivitet.ADMO, "Oppfølging på arbeidsplassen", false),
    OPPFMARB(GruppeAktivitet.SAK, "Oppfølging for sykmeldt arbeidstaker", false),
    OPPFNAV(GruppeAktivitet.ADMO, "Oppfølging i regi av Nav", false),
    OPPFPLAN(GruppeAktivitet.SPES, "SF1 - Arbeidsgivers oppfølgingsplan", false),
    OPPFUARB(GruppeAktivitet.SAK, "Oppfølging av sykmeldt uten arbeidsgiver", false),
    OPPLARING(GruppeAktivitet.A14A, "Utdanning", false),
    OPPLT2AAR(GruppeAktivitet.TLTAK, "2-årig opplæringstiltak", true),
    OPPTILTDEL(GruppeAktivitet.SAK, "Følg opp tiltaksdeltakelse", false),
    OUTDEF(GruppeAktivitet.TLTAK, "Ordinær utdanning for enslige forsørgere mv", true),
    PHPL(GruppeAktivitet.SAK, "Handlingsplanlegging", false),
    PLNOPPERS(GruppeAktivitet.SAK, "Planlegg oppfølging - person", false),
    PRAKSKJERM(GruppeAktivitet.TLTAK, "Arbeidspraksis i skjermet virksomhet", true),
    PRAKSORD(GruppeAktivitet.TLTAK, "Arbeidspraksis i ordinær virksomhet", true),
    PV(GruppeAktivitet.TLTAK, "Produksjonsverksted (PV)", false),
    RARB(GruppeAktivitet.SAK, "Kompetansekartlegging arbeidssøker", false),
    RBEHSPES(GruppeAktivitet.SPES2, "Raskere behandling hos spesialist for sykmeldte", false),
    RBIA(GruppeAktivitet.SAK, "Reg. ved bedriftsintern attføring", false),
    RBIO(GruppeAktivitet.SAK, "Kompetanseheving for arbeidstaker", false),
    RDTL(GruppeAktivitet.SAK, "Kjør jobbsøk", false),
    REAKTUFOR(GruppeAktivitet.TLTAK, "Lønnstilskudd - reaktivisering av uførepensjonister", false),
    REFINO(GruppeAktivitet.TLTAK, "Resultatbasert finansiering av oppfølging", true),
    TIDSUBLONN(GruppeAktivitet.TLTAK, "Tidsubestemt lønnstilskudd", false),
    TIINT(GruppeAktivitet.VEIL, "Intro - Formidling og tilrettelegging Individuelt", false),
    TILOPPAVT(GruppeAktivitet.EGEN, "Tilretteleggings- og oppfølgingsavtale", false),
    TILPERBED(GruppeAktivitet.TLTAK, "Tilretteleggingstilskudd for arbeidssøker", false),
    TILRARBPL(GruppeAktivitet.A14A, "Tilrettelegging av arbeidsplass", false),
    TILRETARB(GruppeAktivitet.ANN, "Tilretteleggingsgaranti for arbeidsgiver", false),
    TILRETPERS(GruppeAktivitet.EGEN, "Tilretteleggingsgaranti for person", false),
    TILRETTEL(GruppeAktivitet.TLTAK, "Tilrettelegging for arbeidstaker", false),
    TILRET_ARB(GruppeAktivitet.SPES, "Tilrettelegging på arbeidsplassen", false),
    TILRTILSK(GruppeAktivitet.TLTAK, "Forebyggings- og tilretteleggingstilskudd IA virksomheter og BHT-honorar", false),
    TILR_TILSK(GruppeAktivitet.SPES, "Tilretteleggingstilskudd", false),
    TILSBHT(GruppeAktivitet.SPES, "Tilskudd til BHT", false),
    TILSJOBB(GruppeAktivitet.TLTAK, "Tilskudd til sommerjobb", false),
    TIUARK(GruppeAktivitet.VEIL, "UARK - Formidling og tilrettelegging Individuelt", false),
    TLFREKBIST(GruppeAktivitet.ANN, "Telefonkontakt rekrutteringsbistand", false),
    TLFTILT(GruppeAktivitet.ANN, "Telefonkontakt tiltak", false),
    TOLKHLP(GruppeAktivitet.SPES2, "Tolkehjelp", false),
    UFØREPENLØ(GruppeAktivitet.TLTAK, "Uførepensjon som lønnstilskudd", false),
    UGARK(GruppeAktivitet.VEIL, "veiledningsmøte ved Nav Arbeidsrådgivning", false),
    UGSYA(GruppeAktivitet.VEIL, "veiledningsmøte ved SYA", false),
    UTBHLETTPS(GruppeAktivitet.TLTAK, "Utredning/behandling lettere psykiske lidelser", false),
    UTBHPSLD(GruppeAktivitet.TLTAK, "Utredning/behandling lettere psykiske og sammensatte lidelser", false),
    UTBHSAMLI(GruppeAktivitet.TLTAK, "Utredning/behandling sammensatte lidelser", false),
    UTDPERMVIK(GruppeAktivitet.TLTAK, "Utdanningspermisjoner", false),
    UTDYRK(GruppeAktivitet.TLTAK, "Utdanning", true),
    UTRSPES(GruppeAktivitet.VEIL, "Utredning i spesialenhet / andrelinje", false),
    UTSYA(GruppeAktivitet.VEIL, "SYA - Utvei", false),
    UTVAOONAV(GruppeAktivitet.TLTAK, "Arbeid med støtte", true),
    UTVOPPFOPL(GruppeAktivitet.TLTAK, "Utvidet oppfølging i opplæring", true),
    VALJ(GruppeAktivitet.SPES, "Veiledning i annenlinje", false),
    VALS(GruppeAktivitet.TLTAK, "Formidlingstjenester - Ventelønn", false),
    VARLONTIL(GruppeAktivitet.TLTAK, "Varig lønnstilskudd", false),
    VASV(GruppeAktivitet.TLTAK, "Varig tilrettelagt arbeid i skjermet virksomhet", false),
    VATIAROR(GruppeAktivitet.TLTAK, "Varig tilrettelagt arbeid i ordinær virksomhet", false),
    VENTBEHAN(GruppeAktivitet.EGEN, "Venter på behandling", false),
    VGINT(GruppeAktivitet.VEIL, "veiledningsmøte ved Nav Intro", false),
    VGUARK(GruppeAktivitet.VEIL, "veiledningsmøte ved UARK", false),
    VGVAL(GruppeAktivitet.VEIL, "veiledningsmøte ved Nav lokalt", false),
    VHPL(GruppeAktivitet.SPES, "Handlingsplanlegging", false),
    VIINT(GruppeAktivitet.VEIL, "Intro - Veiledning Individuelt", false),
    VIKARBLED(GruppeAktivitet.TLTAK, "Utdanningsvikariater", false),
    VIUARK(GruppeAktivitet.VEIL, "UARK - Veiledning Individuelt", false),
    VSAM(GruppeAktivitet.SAK, "Individuell samtale", false),
    VURDTILT(GruppeAktivitet.SAK, "Vurder tiltaksbehov", false),
    VV(GruppeAktivitet.TLTAK, "Varig vernet arbeid (VVA)", false),
    YHEMMOFF(GruppeAktivitet.TLTAK, "Sysselsettingstiltak for yrkeshemmede", false),
    IA_VURD(GruppeAktivitet.SAK, "IA Vurder IA-status for arbeidsgiver", false),
    IFSYA(GruppeAktivitet.VEIL, "SYA - Formidling og tilrettelegging Individuelt", false),
    IGVAL(GruppeAktivitet.VEIL, "informasjonsmøte ved Nav lokalt", false),
    IIVAL(GruppeAktivitet.VEIL, "Lokal - Informasjon Individuelt", false),
    INDJOBSTOT(GruppeAktivitet.TLTAK, "Individuell jobbstøtte (IPS)", true),
    INDOP(GruppeAktivitet.SAK, "Individuell oppfølging", false),
    INDOPPFAG(GruppeAktivitet.TLTAK, "Oppfølging", true),
    INDOPPFOLG(GruppeAktivitet.TLTAK, "Individuelt oppfølgingstiltak", false),
    INDOPPFSP(GruppeAktivitet.TLTAK, "Oppfølging - sykmeldt arbeidstaker", true),
    INDOPPRF(GruppeAktivitet.TLTAK, "Resultatbasert finansiering av formidlingsbistand", false),
    INFMO(GruppeAktivitet.ANN, "Informasjonsmøte - omstilling nedbemanning", false),
    INFOOMST(GruppeAktivitet.ANN, "Informasjonsmøte - omstilling og nedbemanning", false),
    INKLUTILS(GruppeAktivitet.TLTAK, "Inkluderingstilskudd", false),
    INSTIT_B(GruppeAktivitet.SPES, "Institusjonsopphold - behandling", false),
    INSTIT_F(GruppeAktivitet.SPES, "Institusjonsopphold - fengsel", false),
    INSTIT_R(GruppeAktivitet.SPES, "Institusjonsopphold - rehabilitering/opptrening", false),
    INST_S(GruppeAktivitet.TLTAK, "Nye plasser institusjonelle tiltak", false),
    INTV(GruppeAktivitet.SPES, "Intervju", false),
    IOVAL(GruppeAktivitet.VEIL, "Lokal - Veiledning Individuelt", false),
    IPSUNG(GruppeAktivitet.TLTAK, "Individuell karrierestøtte (IPS Ung)", true),
    ITARK(GruppeAktivitet.VEIL, "ARK - Individuell tiltaksoppfølging", false),
    ITGRTILS(GruppeAktivitet.TLTAK, "Integreringstilskudd", false),
    ITSYA(GruppeAktivitet.VEIL, "SYA - Individuell tiltaksoppfølging", false),
    IUARK(GruppeAktivitet.VEIL, "ARK - Veiledning Individuelt", false),
    IUSYA(GruppeAktivitet.VEIL, "SYA - Veiledning Individuelt", false),
    JOBBBONUS(GruppeAktivitet.TLTAK, "Jobbklubb med bonusordning", false),
    JOBBFOKUS(GruppeAktivitet.TLTAK, "Jobbfokus/Utvidet formidlingsbistand", false),
    JOBBK(GruppeAktivitet.TLTAK, "Jobbklubb", true),
    JOBBKBONUS(GruppeAktivitet.TLTAK, "Jobbklubb med bonusordning", false),
    JOBBKLUBB(GruppeAktivitet.TLTAK, "Intern jobbklubb", false),
    JOBBMESS(GruppeAktivitet.ANN, "Jobbmesse", false),
    JOBBS(GruppeAktivitet.A14A, "Jobbsøking", false),
    JOBBSKAP(GruppeAktivitet.TLTAK, "Jobbskapingsprosjekter", false),
    JOBBSOK(GruppeAktivitet.EGEN, "Jobbsøking", false),
    KARTL(GruppeAktivitet.TLTAK, "Kartlegging av norskkunnskaper", false),
    KAT(GruppeAktivitet.TLTAK, "Formidlingstjenester", false),
    KJAVKL(GruppeAktivitet.EGEN, "Forsøk kjerneoppgaver avklaring", false),
    KJOPPF(GruppeAktivitet.EGEN, "Forsøk kjerneoppgaver oppfølging", false),
    KOMARB(GruppeAktivitet.SPES2, "Kommunale arbeidsrettede tiltak", false),
    KOMAVTILT(GruppeAktivitet.TLTAK, "Kommunale avklaringstiltak", false),
    KOMOPPF(GruppeAktivitet.SPES2, "Kommunal oppfølging", false),
    KOMPKART(GruppeAktivitet.SAK, "Kompetansekartlegging og jobbsøk", false),
    KOMTILT(GruppeAktivitet.SPES2, "Kommunale tiltak", false),
    KOMTILTA(GruppeAktivitet.SPES2, "Andre kommunale tiltak", false),
    KONTSKJE(GruppeAktivitet.ANN, "Kontaktskjema", false),
    KRIMOMS(GruppeAktivitet.SPES2, "Kriminalomsorg", false),
    KURS(GruppeAktivitet.EGEN, "Egenfinansiert kurs", false),
    KURSKOMM(GruppeAktivitet.SPES, "Kurs i regi av kommunen", false),
    KVALPROG(GruppeAktivitet.SPES2, "Kvalifiseringsprogrammet", false),
    KVPAKT(GruppeAktivitet.SPES2, "Andre aktiviteter i KVP", false),
}
