package no.nav.tilleggsstonader.kontrakter.felles

enum class Hovedytelse {
    AAP,
    OVERGANGSSTØNAD,
    GJENLEVENDEPENSJON,
    UFØRETRYGD,
    TILTAKSPENGER,
    UNGDOMSPROGRAMMET,
    AKTIVITETSPENGER,
    DAGPENGER,
    SYKEPENGER,
    KVALIFISERINGSSTØNAD,
    INGEN_PENGESTØTTE,
    INGEN_PASSENDE_ALTERNATIVER,
}
