name: Bygg app og kjør tester

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: "Bygger prosjektet, sjekker linting og kjører testene"
    uses: navikt/tilleggsstonader/.github/workflows/java-build-and-test.yml@main
